CREATE DATABASE buduanwangde315;

CREATE TABLE IF NOT EXISTS `user` (
    id SMALLINT UNSIGNED KEY AUTO_INCREMENT,
    username VARCHAR(32) UNIQUE NOT NULL,
    name VARCHAR(32) NOT NULL,
    password VARCHAR(32) NOT NULL,
    rank SMALLINT UNSIGNED NOT NULL DEFAULT 0
)ENGINE=INNODB CHARSET=UTF8;